version: "3.8"

services:
  db:
    image: postgres:17.3-alpine
    container_name: dictionary-db-container
    ports:
      - "5431:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

  db-test:
    image: postgres:17.3-alpine
    container_name: dictionary-test-db-container
    ports:
      - "5430:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_TEST_NAME}
      POSTGRES_USER: ${DB_TEST_USER}
      POSTGRES_PASSWORD: ${DB_TEST_PASS}
    # volume:
    #   - db-test-data:/var/lib/postgresql/data
    restart: unless-stopped
      

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dictionary-app-container
    ports:
      - "8080:8080"
    depends_on:
      - db
      - db-test
    env_file:
      - .env
    restart: unless-stopped

volumes:
  db-data:
